### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by py444** [jpdillingham/BigFont#1]
awesome job 
is there any way to change font size ?

**Comment by jpdillingham** [comment]
Thanks!

I've included an example that uses a smaller font.  If you'd like it to be smaller than that unfortunately the only way is to manually edit the alphabet.

**Comment by jpdillingham** [comment]
I've just added an update with a smaller font size.  Readability is suffering so I don't think it is possible to push it any lower without switching to a simple block lettering style.
